aliases:
  cat: pygmentize -g
  ls: eza
  lg: lazygit
  dig: doggo
  j: just
  jg: just -g
  gpc: gh pr create
  gpv: gh pr view
  gpm: gh pr merge && git pull --ff-only

environment:
  # path
  BUN_INSTALL: $HOME/.bun
  PNPM_HOME: $HOME/Library/pnpm
  ANDROID_HOME: $HOME/Library/Android/sdk
  MISE_HOME: $HOME/.local/share/mise/shims

  # zplug
  ZPLUG_HOME: $HOMEBREW_PREFIX/opt/zplug

  # dotenv
  ZSH_DOTENV_FILE: .env.local
  ZSH_DOTENV_PROMPT: false

paths:
  # node
  - $PNPM_HOME
  - $BUN_INSTALL/bin
  # android studio
  - $ANDROID_HOME/tools
  - $ANDROID_HOME/tools/bin
  - $ANDROID_HOME/platform-tools

zplug_plugins:
  - name: plugins/mise
    from: oh-my-zsh
  - name: plugins/starship
    from: oh-my-zsh
  - name: plugins/dotenv
    from: oh-my-zsh
  - name: lib/key-bindings
    from: oh-my-zsh
  - name: lib/directories
    from: oh-my-zsh
  - name: plugins/bun
    from: oh-my-zsh
    defer: 2
  - name: plugins/git
    from: oh-my-zsh
    defer: 2
  - name: plugins/aws
    from: oh-my-zsh
    defer: 2
  - name: plugins/docker
    from: oh-my-zsh
    defer: 2
  - name: plugins/gh
    from: oh-my-zsh
    defer: 2
  - name: lib/completion
    from: oh-my-zsh
    defer: 2
  - name: zsh-users/zsh-autosuggestions
    defer: 3
  - name: zsh-users/zsh-syntax-highlighting
    defer: 3

mcp_servers:
  connector-database:
    type: stdio
    command: mise
    args:
      - x
      - npm:@bytebase/dbhub
      - --
      - dbhub
      - --transport
      - stdio
      - --config
      - ~/.config/dbhub/dbhub.toml
  documentation-aws:
    type: stdio
    command: mise
    args:
      - x
      - pipx:awslabs.aws-documentation-mcp-server
      - --
      - awslabs.aws-documentation-mcp-server
    environment:
      AWS_DOCUMENTATION_PARTITION: aws
  documentation-shadcn:
    type: stdio
    command: mise
    args:
      - x
      - npm:shadcn
      - --
      - shadcn
      - mcp
  tools-chrome:
    type: stdio
    command: mise
    args:
      - x
      - npm:chrome-devtools-mcp
      - --
      - chrome-devtools-mcp
      - --autoConnect
  tools-pyhub-mcptools:
    type: stdio
    command: mise
    args:
      - x
      - pip:pyhub.mcptools
      - --
      - pyhub.mcptools
      - run
  tools-figma:
    type: http
    url: https://mcp.figma.com/mcp
  tools-figma-desktop:
    type: http
    url: http://127.0.0.1:3845/mcp
