name: container

services:
  mysql:
    image: mysql:8
    command: --local-infile=1
    environment:
      MYSQL_USER: eunsol
      MYSQL_ROOT_PASSWORD: eunsol

  postgresql:
    image: postgres:18
    environment:
      POSTGRES_USER: eunsol
      POSTGRES_PASSWORD: eunsol

  minio:
    image: pgsty/minio
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: eunsol
      MINIO_ROOT_PASSWORD: eunsol_eunsol
