[settings]
install_before = "1d"

[tools]
# Languages
node = "26"
java = "27"
python = "3.14"

# package manager
bun = "1.4.2"
yarn = "4.18.1"
uv = "0.12.19"
pnpm = "12.6.0"

# CLI
gh = "latest"
mas = "latest"
turbo = "latest"
mysql = "latest"
flyway = "latest"
vercel = "latest"
chezmoi = "latest"
lazygit = "latest"
portless = "latest"
prettier = "latest"
sshuttle = "latest"
xcodegen = "latest"
1password = "latest"
"cloud-sql-proxy" = "latest"

# Coding Tools
codex = "latest"
claude = "latest"

# Tools
yq = "latest"
fd = "latest"
bat = "latest"
eza = "latest"
just = "latest"
doggo = "latest"
ripgrep = "latest"
"aqua:minio/mc" = "latest"
"pipx:pygments" = "latest"
"npm:prettier-pnp" = "latest"
"aqua:ast-grep/ast-grep" = "latest"

# MCP
"npm:@bytebase/dbhub" = "latest"
"npm:computer-use-mcp" = "latest"
"npm:chrome-devtools-mcp" = "latest"

# Ghostty
starship = "latest"
